### PR TITLE
Get installed_version from PMS executable instead of synopkg

### PR DESCRIPTION
**Pull request by oscaritoro**
This PR intends to solve [Issue#28](https://github.com/cowboy/synology-update-plex/issues/28). For more information please review the comments associated with [Issue#28](https://github.com/cowboy/synology-update-plex/issues/28)

### CODE REVIEW

**Comment by oscaritoro** [comment]
Tested on my DS918+

**Comment by emmanuelrflores** [comment]
If it helps at all, I tried this on my DS1019+ and it worked successfully in detecting the same version was installed.

**Comment by bolshukhin** [comment]
I have an update running, but I have bug notifications. Errors related to Plex's work status

**Comment by cowboy** [comment]
It looks like this issue was resolved by 9f1e759c22e034033dacfe2f561bcd954ae9b6eb. Please let me know if that's not the case!

**Pull request closed without merging**
