### PR TITLE
Add compatibility with syno_hw_version DS216j-j

### PR DESCRIPTION
**Pull request by gioxx**
Add compatibility with DS216j.

### CODE REVIEW

**Comment by cowboy** [comment]
Sorry for the late response - can you reopen this PR so the build check will run? If it passes, I'll merge it in!

**Comment by cowboy** [comment]
Can you add a corresponding test into `test/get_arch.bats`? Thanks!

**Comment by gioxx** [comment]
I should have done that.

**Comment by cowboy** [comment]
I'm not familiar with this model, but I think you need to add a test for `DS216j-j` instead of changing the existing `DS216j` test. Either way, the test is failing!

**Comment by gioxx** [comment]
I just can't figure out where the problem is.
```
gioxx@Syno:~$ more /proc/sys/kernel/syno_hw_version
DS216j-j
gioxx@Syno:~$ uname -m
armv7l
```
Any change I make in get_arch.bats turns into a failure at check.

**Comment by gioxx** [comment]
Finally, I figured out where the anomaly was and fixed it 😄

**Comment by cowboy** [comment]
Released! https://github.com/cowboy/synology-update-plex/releases/tag/v1.1.1

**Pull request merged**
