### PR TITLE
Update update-plex.sh

### PR DESCRIPTION
**Pull request by sodhi**
Not all versions of wget (which differs between DSM versions) support "--no-show-progress", but "-q" always works (afaik). Your version fails on i.e. DSM 6.1.7.

### CODE REVIEW

**Comment by cowboy** [comment]
Well, `--quiet` (`-q`) and `--no-show-progress` have different outputs, and I don't want it to be completely silent. What version does `wget --version` output for you?

**Comment by cowboy** [comment]
What does this command output for you?

```sh
wget --no-verbose https://downloads.plex.tv/plex-media-server-new/1.19.1.2701-6327e27bf/synology/PlexMediaServer-1.19.1.2701-6327e27bf-x86.spk -P /tmp
```

**Comment by sodhi** [comment]
**--no-verbose:**

> sodhi@NAS $ wget --no-verbose https://downloads.plex.tv/plex-media-server-new/1.19.1.2701-6327e27bf/synology/PlexMediaServer-1.19.1.2701-6327e27bf-x86.spk -P /tmp

> 2020-04-28 13:34:06 URL:https://downloads.plex.tv/plex-media-server-new/1.19.1.2701-6327e27bf/synology/PlexMediaServer-1.19.1.2701-6327e27bf-x86.spk [100341760/100341760] -> "/tmp/PlexMediaServer-1.19.1.2701-6327e27bf-x86.spk.1" [1]

**--version**

>GNU Wget 1.15 built on linux-gnu.

>+digest +https +ipv6 -iri +large-file -nls +ntlm +opie +ssl/openssl

**Comment by cowboy** [comment]
Ok. Update your PR to change `--no-show-progress` to `--no-verbose` instead of `-q` and I'll merge it! Note: you'll also need to remove the ` | awk '!/--| saved |^$/'` bit at the end of the line, since that's no longer relevant.

**Comment by cowboy** [comment]
I suppose the line should just be

```sh
wget --no-verbose "$package_url" -P $tmp_dir
```

**Comment by sodhi** [comment]
Done. I hope correctly. Not too used to github ;-)

**Pull request merged**
